### ISSUE TITLE
「値」という言葉の使い方について

### ISSUE THREAD

**Issue by toku345** [clj-nakano/learndatalogtoday#3]
**Chapter1: 基本のクエリ** 内で Datomの4要素の中の1つとして値(Value) 出てきますが、
説明文内で「値」という単語が出てくるとレコードか何かを指しているんだっけ？と勘ぐってしまい、Value要素を指していることに気がつくのにちょっと時間がかかってしまいました。

![datomic](https://user-images.githubusercontent.com/3142849/34367528-3d44bd48-eaef-11e7-9f5a-f43cb154411c.png)

`datomの値(Value)` みたいな感じで Value属性 のことを指していることをより明確にしていただくとわかりやすいかも、と感じましたがいかがでしょうか？

**Comment by k2n** [comment]
datomの定義のところで、"値(Value)"と記述しているので、紐付けて読んでいただけるかなという期待のもとに訳していたのですが、紛らわしいですよね。ご指摘のようにValueであることを併記した上で、"167"も含めておけばよりわかりやすいですね。

**Comment by k2n** [comment]
変更をherokuにpublishしました。当初はなるだけ原文に忠実に、と思って訳していたのですが、原作者から改変の許諾も頂いたので、よりわかりやすくしていきたいと思います。

**Comment by toku345** [comment]
@k2n さん
早速のご対応ありがとうございます！めっちゃわかりやすくなってます😭
