### ISSUE TITLE
Chap3:「パラメータ化されたクエリ」の問3について

### ISSUE THREAD

**Issue by toku345** [clj-nakano/learndatalogtoday#4]
こちらの問題なのですが、
![datomic](https://user-images.githubusercontent.com/3142849/34427615-aa90f224-ec87-11e7-8e8e-1c8c2c8b93ce.png)

`レーティングが一致する` の箇所が 、`:movie/rating` みたいな attribute があってこれと入力値#2で渡されたレーティングと一致させる必要があるのかな？と、ちょっと混乱してしまいました。

「その俳優がキャストされている映画のタイトルとそれに紐づくレーティングを検索せよ」みたいなほうが自然に感じるのですが、いかがでしょうか？

**Comment by k2n** [comment]
フィードバックありがとうございます。原文からも正しく訳せていなかったですし、日本語として意味が通じなかったですね。修正しましたのでご確認ください。

**Comment by toku345** [comment]
ご対応ありがとうございます！！
問題の意図がわかるようになりました。
